class VegetedlesText {
  List<String> name = <String>[
    'Помидор',
    'Огурец',
    'Морковь',
    'Перец',
    'Брокколи',
    'Цветная капуста',
    'Шпинат',
    'Картофель',
    'Лук',
    'Чеснок',
    'Баклажан',
    'Цукини',
    'Тыква',
    'Редис',
    'Свекла',
    'Репа',
    'Горох',
    'Кукуруза',
  ];
  List<String> descrioption = <String>[
    'помидор',
    'огурец',
    'морковь',
    'перец',
    'брокколи',
    'цветная капуста',
    'шпинат',
    'картофель',
    'лук',
    'чеснок',
    'баклажан',
    'цукини',
    'тыква',
    'редис',
    'свекла',
    'репа',
    'горох',
    'кукуруза',
  ];
  List<String> photo = <String>[
    'assets/images/pomidor.jpeg',
    'assets/images/ogurets.jpeg',
    'assets/images/morkov.jpeg',
    'assets/images/perets.jpeg',
    'assets/images/brokli.jpeg',
    'assets/images/svetlaakapusta.jpeg',
    'assets/images/shpinat.jpeg',
    'assets/images/kartoshka.jpeg',
    'assets/images/luk.jpeg',
    'assets/images/chesnok.jpeg',
    'assets/images/baclajan.jpeg',
    'assets/images/sukini.jpeg',
    'assets/images/tikva.jpeg',
    'assets/images/redis.jpeg',
    'assets/images/svekla.jpeg',
    'assets/images/repa.jpeg',
    'assets/images/goroh.jpeg',
    'assets/images/kukuruza.jpeg',
  ];
}
