class FruitsText {
  List<String> name = <String>[
    'Яблоко',
    'Абрикос',
    'Авокадо',
    'Банан',
    'Ежевика',
    'Черная смородина',
    'Черника',
    'Бойзенова ягода',
    'Вишня',
    'Клементин',
    'Кокос',
    'Клюква',
    'Финик',
    'Драконов фрукт',
    'Дуриан',
    'Бузина',
    'Фейхоа',
    'Инжир',
    'Виноград',
  ];
  List<String> description = <String>[
    'яблоко',
    'абрикос',
    'авокадо',
    'банан',
    'ежевика',
    'черная смородина',
    'черника',
    'бойзенова ягода',
    'вишня',
    'клементин',
    'кокос',
    'клюква',
    'финик',
    'драконов фрукт',
    'дуриан',
    'бузина',
    'фейхоа',
    'инжир',
    'виноград',
  ];

  List<String> photos = <String>[
    'assets/images/apple.jpeg',
    'assets/images/abrikos.jpeg',
    'assets/images/avakada.jpeg',
    'assets/images/banan.jpeg',
    'assets/images/ejevika.jpeg',
    'assets/images/cherna.jpeg',
    'assets/images/chernika.jpeg',
    'assets/images/byzina.jpeg',
    'assets/images/vishnia.jpeg',
    'assets/images/klementin.jpeg',
    'assets/images/kokos.jpeg',
    'assets/images/klukva.jpeg',
    'assets/images/finik.jpeg',
    'assets/images/drakon.jpeg',
    'assets/images/durian.jpg',
    'assets/images/bouzenova.jpeg',
    'assets/images/fehoa.jpeg',
    'assets/images/injir.jpeg',
    'assets/images/vinograd.jpeg',
    'assets/images/Banner.png',
    'assets/images/klukva.jpeg',
  ];
}
